-- NOT USE

INSERT INTO currency(id,country,currency,code) VALUES (1,'Afghanistan','Afghan afghani','AFN');
INSERT INTO currency(id,country,currency,code) VALUES (2,'Akrotiri and Dhekelia (UK)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (3,'Aland Islands (Finland)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (4,'Albania','Albanian lek','ALL');
INSERT INTO currency(id,country,currency,code) VALUES (5,'Algeria','Algerian dinar','DZD');
INSERT INTO currency(id,country,currency,code) VALUES (6,'American Samoa (USA)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (7,'Andorra','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (8,'Angola','Angolan kwanza','AOA');
INSERT INTO currency(id,country,currency,code) VALUES (9,'Anguilla (UK)','East Caribbean dollar','XCD');
INSERT INTO currency(id,country,currency,code) VALUES (10,'Antigua and Barbuda','East Caribbean dollar','XCD');
INSERT INTO currency(id,country,currency,code) VALUES (11,'Argentina','Argentine peso','ARS');
INSERT INTO currency(id,country,currency,code) VALUES (12,'Armenia','Armenian dram','AMD');
INSERT INTO currency(id,country,currency,code) VALUES (13,'Aruba (Netherlands)','Aruban florin','AWG');
INSERT INTO currency(id,country,currency,code) VALUES (14,'Ascension Island (UK)','Saint Helena pound','SHP');
INSERT INTO currency(id,country,currency,code) VALUES (15,'Australia','Australian dollar','AUD');
INSERT INTO currency(id,country,currency,code) VALUES (16,'Austria','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (17,'Azerbaijan','Azerbaijan manat','AZN');
INSERT INTO currency(id,country,currency,code) VALUES (18,'Bahamas','Bahamian dollar','BSD');
INSERT INTO currency(id,country,currency,code) VALUES (19,'Bahrain','Bahraini dinar','BHD');
INSERT INTO currency(id,country,currency,code) VALUES (20,'Bangladesh','Bangladeshi taka','BDT');
INSERT INTO currency(id,country,currency,code) VALUES (21,'Barbados','Barbadian dollar','BBD');
INSERT INTO currency(id,country,currency,code) VALUES (22,'Belarus','Belarusian ruble','BYN');
INSERT INTO currency(id,country,currency,code) VALUES (23,'Belgium','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (24,'Belize','Belize dollar','BZD');
INSERT INTO currency(id,country,currency,code) VALUES (25,'Benin','West African CFA franc','XOF');
INSERT INTO currency(id,country,currency,code) VALUES (26,'Bermuda (UK)','Bermudian dollar','BMD');
INSERT INTO currency(id,country,currency,code) VALUES (27,'Bhutan','Bhutanese ngultrum','BTN');
INSERT INTO currency(id,country,currency,code) VALUES (28,'Bolivia','Bolivian boliviano','BOB');
INSERT INTO currency(id,country,currency,code) VALUES (29,'Bonaire (Netherlands)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (30,'Bosnia and Herzegovina','Bosnia and Herzegovina convertible mark','BAM');
INSERT INTO currency(id,country,currency,code) VALUES (31,'Botswana','Botswana pula','BWP');
INSERT INTO currency(id,country,currency,code) VALUES (32,'Brazil','Brazilian real','BRL');
INSERT INTO currency(id,country,currency,code) VALUES (33,'British Indian Ocean Territory (UK)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (34,'British Virgin Islands (UK)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (35,'Brunei','Brunei dollar','BND');
INSERT INTO currency(id,country,currency,code) VALUES (36,'Bulgaria','Bulgarian lev','BGN');
INSERT INTO currency(id,country,currency,code) VALUES (37,'Burkina Faso','West African CFA franc','XOF');
INSERT INTO currency(id,country,currency,code) VALUES (38,'Burundi','Burundi franc','BIF');
INSERT INTO currency(id,country,currency,code) VALUES (39,'Cabo Verde','Cape Verdean escudo','CVE');
INSERT INTO currency(id,country,currency,code) VALUES (40,'Cambodia','Cambodian riel','KHR');
INSERT INTO currency(id,country,currency,code) VALUES (41,'Cameroon','Central African CFA franc','XAF');
INSERT INTO currency(id,country,currency,code) VALUES (42,'Canada','Canadian dollar','CAD');
INSERT INTO currency(id,country,currency,code) VALUES (43,'Caribbean Netherlands (Netherlands)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (44,'Cayman Islands (UK)','Cayman Islands dollar','KYD');
INSERT INTO currency(id,country,currency,code) VALUES (45,'Central African Republic','Central African CFA franc','XAF');
INSERT INTO currency(id,country,currency,code) VALUES (46,'Chad','Central African CFA franc','XAF');
INSERT INTO currency(id,country,currency,code) VALUES (47,'Chatham Islands (New Zealand)','New Zealand dollar','NZD');
INSERT INTO currency(id,country,currency,code) VALUES (48,'Chile','Chilean peso','CLP');
INSERT INTO currency(id,country,currency,code) VALUES (49,'China','Chinese Yuan Renminbi','CNY');
INSERT INTO currency(id,country,currency,code) VALUES (50,'Christmas Island (Australia)','Australian dollar','AUD');
INSERT INTO currency(id,country,currency,code) VALUES (51,'Cocos (Keeling) Islands (Australia)','Australian dollar','AUD');
INSERT INTO currency(id,country,currency,code) VALUES (52,'Colombia','Colombian peso','COP');
INSERT INTO currency(id,country,currency,code) VALUES (53,'Comoros','Comorian franc','KMF');
INSERT INTO currency(id,country,currency,code) VALUES (54,'Congo, Democratic Republic of the','Congolese franc','CDF');
INSERT INTO currency(id,country,currency,code) VALUES (55,'Congo, Republic of the','Central African CFA franc','XAF');
INSERT INTO currency(id,country,currency,code) VALUES (56,'Cook Islands (New Zealand)','Cook Islands dollar','---');
INSERT INTO currency(id,country,currency,code) VALUES (57,'Costa Rica','Costa Rican colon','CRC');
INSERT INTO currency(id,country,currency,code) VALUES (58,'Cote d''Ivoire','West African CFA franc','XOF');
INSERT INTO currency(id,country,currency,code) VALUES (59,'Croatia','Croatian kuna','HRK');
INSERT INTO currency(id,country,currency,code) VALUES (60,'Cuba','Cuban peso','CUP');
INSERT INTO currency(id,country,currency,code) VALUES (61,'Curacao (Netherlands)','Netherlands Antillean guilder','ANG');
INSERT INTO currency(id,country,currency,code) VALUES (62,'Cyprus','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (63,'Czechia','Czech koruna','CZK');
INSERT INTO currency(id,country,currency,code) VALUES (64,'Denmark','Danish krone','DKK');
INSERT INTO currency(id,country,currency,code) VALUES (65,'Djibouti','Djiboutian franc','DJF');
INSERT INTO currency(id,country,currency,code) VALUES (66,'Dominica','East Caribbean dollar','XCD');
INSERT INTO currency(id,country,currency,code) VALUES (67,'Dominican Republic','Dominican peso','DOP');
INSERT INTO currency(id,country,currency,code) VALUES (68,'Ecuador','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (69,'Egypt','Egyptian pound','EGP');
INSERT INTO currency(id,country,currency,code) VALUES (70,'El Salvador','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (71,'Equatorial Guinea','Central African CFA franc','XAF');
INSERT INTO currency(id,country,currency,code) VALUES (72,'Eritrea','Eritrean nakfa','ERN');
INSERT INTO currency(id,country,currency,code) VALUES (73,'Estonia','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (74,'Eswatini (formerly Swaziland)','Swazi lilangeni','SZL');
INSERT INTO currency(id,country,currency,code) VALUES (75,'Ethiopia','Ethiopian birr','ETB');
INSERT INTO currency(id,country,currency,code) VALUES (76,'Falkland Islands (UK)','Falkland Islands pound','FKP');
INSERT INTO currency(id,country,currency,code) VALUES (77,'Faroe Islands (Denmark)','Faroese krona','---');
INSERT INTO currency(id,country,currency,code) VALUES (78,'Fiji','Fijian dollar','FJD');
INSERT INTO currency(id,country,currency,code) VALUES (79,'Finland','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (80,'France','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (81,'French Guiana (France)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (82,'French Polynesia (France)','CFP franc','XPF');
INSERT INTO currency(id,country,currency,code) VALUES (83,'Gabon','Central African CFA franc','XAF');
INSERT INTO currency(id,country,currency,code) VALUES (84,'Gambia','Gambian dalasi','GMD');
INSERT INTO currency(id,country,currency,code) VALUES (85,'Georgia','Georgian lari','GEL');
INSERT INTO currency(id,country,currency,code) VALUES (86,'Germany','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (87,'Ghana','Ghanaian cedi','GHS');
INSERT INTO currency(id,country,currency,code) VALUES (88,'Gibraltar (UK)','Gibraltar pound','GIP');
INSERT INTO currency(id,country,currency,code) VALUES (89,'Greece','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (90,'Greenland (Denmark)','Danish krone','DKK');
INSERT INTO currency(id,country,currency,code) VALUES (91,'Grenada','East Caribbean dollar','XCD');
INSERT INTO currency(id,country,currency,code) VALUES (92,'Guadeloupe (France)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (93,'Guam (USA)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (94,'Guatemala','Guatemalan quetzal','GTQ');
INSERT INTO currency(id,country,currency,code) VALUES (95,'Guernsey (UK)','Guernsey Pound','GGP');
INSERT INTO currency(id,country,currency,code) VALUES (96,'Guinea','Guinean franc','GNF');
INSERT INTO currency(id,country,currency,code) VALUES (97,'Guinea-Bissau','West African CFA franc','XOF');
INSERT INTO currency(id,country,currency,code) VALUES (98,'Guyana','Guyanese dollar','GYD');
INSERT INTO currency(id,country,currency,code) VALUES (99,'Haiti','Haitian gourde','HTG');
INSERT INTO currency(id,country,currency,code) VALUES (100,'Honduras','Honduran lempira','HNL');
INSERT INTO currency(id,country,currency,code) VALUES (101,'Hong Kong (China)','Hong Kong dollar','HKD');
INSERT INTO currency(id,country,currency,code) VALUES (102,'Hungary','Hungarian forint','HUF');
INSERT INTO currency(id,country,currency,code) VALUES (103,'Iceland','Icelandic krona','ISK');
INSERT INTO currency(id,country,currency,code) VALUES (104,'India','Indian rupee','INR');
INSERT INTO currency(id,country,currency,code) VALUES (105,'Indonesia','Indonesian rupiah','IDR');
INSERT INTO currency(id,country,currency,code) VALUES (106,'International Monetary Fund (IMF)','SDR (Special Drawing Right)','XDR');
INSERT INTO currency(id,country,currency,code) VALUES (107,'Iran','Iranian rial','IRR');
INSERT INTO currency(id,country,currency,code) VALUES (108,'Iraq','Iraqi dinar','IQD');
INSERT INTO currency(id,country,currency,code) VALUES (109,'Ireland','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (110,'Isle of Man (UK)','Manx pound','IMP');
INSERT INTO currency(id,country,currency,code) VALUES (111,'Israel','Israeli new shekel','ILS');
INSERT INTO currency(id,country,currency,code) VALUES (112,'Italy','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (113,'Jamaica','Jamaican dollar','JMD');
INSERT INTO currency(id,country,currency,code) VALUES (114,'Japan','Japanese yen','JPY');
INSERT INTO currency(id,country,currency,code) VALUES (115,'Jersey (UK)','Jersey pound','JEP');
INSERT INTO currency(id,country,currency,code) VALUES (116,'Jordan','Jordanian dinar','JOD');
INSERT INTO currency(id,country,currency,code) VALUES (117,'Kazakhstan','Kazakhstani tenge','KZT');
INSERT INTO currency(id,country,currency,code) VALUES (118,'Kenya','Kenyan shilling','KES');
INSERT INTO currency(id,country,currency,code) VALUES (119,'Kiribati','Australian dollar','AUD');
INSERT INTO currency(id,country,currency,code) VALUES (120,'Kosovo','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (121,'Kuwait','Kuwaiti dinar','KWD');
INSERT INTO currency(id,country,currency,code) VALUES (122,'Kyrgyzstan','Kyrgyzstani som','KGS');
INSERT INTO currency(id,country,currency,code) VALUES (123,'Laos','Lao kip','LAK');
INSERT INTO currency(id,country,currency,code) VALUES (124,'Latvia','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (125,'Lebanon','Lebanese pound','LBP');
INSERT INTO currency(id,country,currency,code) VALUES (126,'Lesotho','Lesotho loti','LSL');
INSERT INTO currency(id,country,currency,code) VALUES (127,'Liberia','Liberian dollar','LRD');
INSERT INTO currency(id,country,currency,code) VALUES (128,'Libya','Libyan dinar','LYD');
INSERT INTO currency(id,country,currency,code) VALUES (129,'Liechtenstein','Swiss franc','CHF');
INSERT INTO currency(id,country,currency,code) VALUES (130,'Lithuania','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (131,'Luxembourg','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (132,'Macau (China)','Macanese pataca','MOP');
INSERT INTO currency(id,country,currency,code) VALUES (133,'Madagascar','Malagasy ariary','MGA');
INSERT INTO currency(id,country,currency,code) VALUES (134,'Malawi','Malawian kwacha','MWK');
INSERT INTO currency(id,country,currency,code) VALUES (135,'Malaysia','Malaysian ringgit','MYR');
INSERT INTO currency(id,country,currency,code) VALUES (136,'Maldives','Maldivian rufiyaa','MVR');
INSERT INTO currency(id,country,currency,code) VALUES (137,'Mali','West African CFA franc','XOF');
INSERT INTO currency(id,country,currency,code) VALUES (138,'Malta','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (139,'Marshall Islands','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (140,'Martinique (France)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (141,'Mauritania','Mauritanian ouguiya','MRU');
INSERT INTO currency(id,country,currency,code) VALUES (142,'Mauritius','Mauritian rupee','MUR');
INSERT INTO currency(id,country,currency,code) VALUES (143,'Mayotte (France)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (144,'Mexico','Mexican peso','MXN');
INSERT INTO currency(id,country,currency,code) VALUES (145,'Micronesia','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (146,'Moldova','Moldovan leu','MDL');
INSERT INTO currency(id,country,currency,code) VALUES (147,'Monaco','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (148,'Mongolia','Mongolian tugrik','MNT');
INSERT INTO currency(id,country,currency,code) VALUES (149,'Montenegro','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (150,'Montserrat (UK)','East Caribbean dollar','XCD');
INSERT INTO currency(id,country,currency,code) VALUES (151,'Morocco','Moroccan dirham','MAD');
INSERT INTO currency(id,country,currency,code) VALUES (152,'Mozambique','Mozambican metical','MZN');
INSERT INTO currency(id,country,currency,code) VALUES (153,'Myanmar (formerly Burma)','Myanmar kyat','MMK');
INSERT INTO currency(id,country,currency,code) VALUES (154,'Namibia','Namibian dollar','NAD');
INSERT INTO currency(id,country,currency,code) VALUES (155,'Nauru','Australian dollar','AUD');
INSERT INTO currency(id,country,currency,code) VALUES (156,'Nepal','Nepalese rupee','NPR');
INSERT INTO currency(id,country,currency,code) VALUES (157,'Netherlands','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (158,'New Caledonia (France)','CFP franc','XPF');
INSERT INTO currency(id,country,currency,code) VALUES (159,'New Zealand','New Zealand dollar','NZD');
INSERT INTO currency(id,country,currency,code) VALUES (160,'Nicaragua','Nicaraguan cordoba','NIO');
INSERT INTO currency(id,country,currency,code) VALUES (161,'Niger','West African CFA franc','XOF');
INSERT INTO currency(id,country,currency,code) VALUES (162,'Nigeria','Nigerian naira','NGN');
INSERT INTO currency(id,country,currency,code) VALUES (163,'Niue (New Zealand)','New Zealand dollar','NZD');
INSERT INTO currency(id,country,currency,code) VALUES (164,'Norfolk Island (Australia)','Australian dollar','AUD');
INSERT INTO currency(id,country,currency,code) VALUES (165,'Northern Mariana Islands (USA)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (166,'North Korea','North Korean won','KPW');
INSERT INTO currency(id,country,currency,code) VALUES (167,'North Macedonia (formerly Macedonia)','Macedonian denar','MKD');
INSERT INTO currency(id,country,currency,code) VALUES (168,'Norway','Norwegian krone','NOK');
INSERT INTO currency(id,country,currency,code) VALUES (169,'Oman','Omani rial','OMR');
INSERT INTO currency(id,country,currency,code) VALUES (170,'Pakistan','Pakistani rupee','PKR');
INSERT INTO currency(id,country,currency,code) VALUES (171,'Palau','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (172,'Palestine','Israeli new shekel','ILS');
INSERT INTO currency(id,country,currency,code) VALUES (173,'Panama','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (174,'Papua New Guinea','Papua New Guinean kina','PGK');
INSERT INTO currency(id,country,currency,code) VALUES (175,'Paraguay','Paraguayan guarani','PYG');
INSERT INTO currency(id,country,currency,code) VALUES (176,'Peru','Peruvian sol','PEN');
INSERT INTO currency(id,country,currency,code) VALUES (177,'Philippines','Philippine peso','PHP');
INSERT INTO currency(id,country,currency,code) VALUES (178,'Pitcairn Islands (UK)','New Zealand dollar','NZD');
INSERT INTO currency(id,country,currency,code) VALUES (179,'Poland','Polish zloty','PLN');
INSERT INTO currency(id,country,currency,code) VALUES (180,'Portugal','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (181,'Puerto Rico (USA)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (182,'Qatar','Qatari riyal','QAR');
INSERT INTO currency(id,country,currency,code) VALUES (183,'Reunion (France)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (184,'Romania','Romanian leu','RON');
INSERT INTO currency(id,country,currency,code) VALUES (185,'Russia','Russian ruble','RUB');
INSERT INTO currency(id,country,currency,code) VALUES (186,'Rwanda','Rwandan franc','RWF');
INSERT INTO currency(id,country,currency,code) VALUES (187,'Saba (Netherlands)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (188,'Saint Barthelemy (France)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (189,'Saint Helena (UK)','Saint Helena pound','SHP');
INSERT INTO currency(id,country,currency,code) VALUES (190,'Saint Kitts and Nevis','East Caribbean dollar','XCD');
INSERT INTO currency(id,country,currency,code) VALUES (191,'Saint Lucia','East Caribbean dollar','XCD');
INSERT INTO currency(id,country,currency,code) VALUES (192,'Saint Martin (France)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (193,'Saint Pierre and Miquelon (France)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (194,'Saint Vincent and the Grenadines','East Caribbean dollar','XCD');
INSERT INTO currency(id,country,currency,code) VALUES (195,'Samoa','Samoan tala','WST');
INSERT INTO currency(id,country,currency,code) VALUES (196,'San Marino','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (197,'Sao Tome and Principe','Sao Tome and Principe dobra','STN');
INSERT INTO currency(id,country,currency,code) VALUES (198,'Saudi Arabia','Saudi Arabian riyal','SAR');
INSERT INTO currency(id,country,currency,code) VALUES (199,'Senegal','West African CFA franc','XOF');
INSERT INTO currency(id,country,currency,code) VALUES (200,'Serbia','Serbian dinar','RSD');
INSERT INTO currency(id,country,currency,code) VALUES (201,'Seychelles','Seychellois rupee','SCR');
INSERT INTO currency(id,country,currency,code) VALUES (202,'Sierra Leone','Sierra Leonean leone','SLL');
INSERT INTO currency(id,country,currency,code) VALUES (203,'Singapore','Singapore dollar','SGD');
INSERT INTO currency(id,country,currency,code) VALUES (204,'Sint Eustatius (Netherlands)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (205,'Sint Maarten (Netherlands)','Netherlands Antillean guilder','ANG');
INSERT INTO currency(id,country,currency,code) VALUES (206,'Slovakia','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (207,'Slovenia','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (208,'Solomon Islands','Solomon Islands dollar','SBD');
INSERT INTO currency(id,country,currency,code) VALUES (209,'Somalia','Somali shilling','SOS');
INSERT INTO currency(id,country,currency,code) VALUES (210,'South Africa','South African rand','ZAR');
INSERT INTO currency(id,country,currency,code) VALUES (211,'South Georgia Island (UK)','Pound sterling','GBP');
INSERT INTO currency(id,country,currency,code) VALUES (212,'South Korea','South Korean won','KRW');
INSERT INTO currency(id,country,currency,code) VALUES (213,'South Sudan','South Sudanese pound','SSP');
INSERT INTO currency(id,country,currency,code) VALUES (214,'Spain','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (215,'Sri Lanka','Sri Lankan rupee','LKR');
INSERT INTO currency(id,country,currency,code) VALUES (216,'Sudan','Sudanese pound','SDG');
INSERT INTO currency(id,country,currency,code) VALUES (217,'Suriname','Surinamese dollar','SRD');
INSERT INTO currency(id,country,currency,code) VALUES (218,'Svalbard and Jan Mayen (Norway)','Norwegian krone','NOK');
INSERT INTO currency(id,country,currency,code) VALUES (219,'Sweden','Swedish krona','SEK');
INSERT INTO currency(id,country,currency,code) VALUES (220,'Switzerland','Swiss franc','CHF');
INSERT INTO currency(id,country,currency,code) VALUES (221,'Syria','Syrian pound','SYP');
INSERT INTO currency(id,country,currency,code) VALUES (222,'Taiwan','New Taiwan dollar','TWD');
INSERT INTO currency(id,country,currency,code) VALUES (223,'Tajikistan','Tajikistani somoni','TJS');
INSERT INTO currency(id,country,currency,code) VALUES (224,'Tanzania','Tanzanian shilling','TZS');
INSERT INTO currency(id,country,currency,code) VALUES (225,'Thailand','Thai baht','THB');
INSERT INTO currency(id,country,currency,code) VALUES (226,'Timor-Leste','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (227,'Togo','West African CFA franc','XOF');
INSERT INTO currency(id,country,currency,code) VALUES (228,'Tokelau (New Zealand)','New Zealand dollar','NZD');
INSERT INTO currency(id,country,currency,code) VALUES (229,'Tonga','Tongan pa’anga','TOP');
INSERT INTO currency(id,country,currency,code) VALUES (230,'Trinidad and Tobago','Trinidad and Tobago dollar','TTD');
INSERT INTO currency(id,country,currency,code) VALUES (231,'Tristan da Cunha (UK)','Pound sterling','GBP');
INSERT INTO currency(id,country,currency,code) VALUES (232,'Tunisia','Tunisian dinar','TND');
INSERT INTO currency(id,country,currency,code) VALUES (233,'Turkey','Turkish lira','TRY');
INSERT INTO currency(id,country,currency,code) VALUES (234,'Turkmenistan','Turkmen manat','TMT');
INSERT INTO currency(id,country,currency,code) VALUES (235,'Turks and Caicos Islands (UK)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (236,'Tuvalu','Australian dollar','AUD');
INSERT INTO currency(id,country,currency,code) VALUES (237,'Uganda','Ugandan shilling','UGX');
INSERT INTO currency(id,country,currency,code) VALUES (238,'Ukraine','Ukrainian hryvnia','UAH');
INSERT INTO currency(id,country,currency,code) VALUES (239,'United Arab Emirates','UAE dirham','AED');
INSERT INTO currency(id,country,currency,code) VALUES (240,'United Kingdom','Pound sterling','GBP');
INSERT INTO currency(id,country,currency,code) VALUES (241,'United States of America','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (242,'Uruguay','Uruguayan peso','UYU');
INSERT INTO currency(id,country,currency,code) VALUES (243,'US Virgin Islands (USA)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (244,'Uzbekistan','Uzbekistani som','UZS');
INSERT INTO currency(id,country,currency,code) VALUES (245,'Vanuatu','Vanuatu vatu','VUV');
INSERT INTO currency(id,country,currency,code) VALUES (246,'Vatican City (Holy See)','European euro','EUR');
INSERT INTO currency(id,country,currency,code) VALUES (247,'Venezuela','Venezuelan bolivar','VES');
INSERT INTO currency(id,country,currency,code) VALUES (248,'Vietnam','Vietnamese dong','VND');
INSERT INTO currency(id,country,currency,code) VALUES (249,'Wake Island (USA)','United States dollar','USD');
INSERT INTO currency(id,country,currency,code) VALUES (250,'Wallis and Futuna (France)','CFP franc','XPF');
INSERT INTO currency(id,country,currency,code) VALUES (251,'Yemen','Yemeni rial','YER');
INSERT INTO currency(id,country,currency,code) VALUES (252,'Zambia','Zambian kwacha','ZMW');
INSERT INTO currency(id,country,currency,code) VALUES (253,'Zimbabwe','United States dollar','USD');