DELETE [dbo].[Currency]

SET IDENTITY_INSERT [dbo].[Currency] ON 
GO
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (1,'Leke', 'ALL', 'Lek');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (2,'Dollars', 'USD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (3,'Afghanis', 'AFN', '؋');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (4,'Pesos', 'ARS', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (5,'Guilders', 'AWG', 'ƒ');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (6,'Dollars', 'AUD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (7,'New Manats', 'AZN', 'ман');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (8,'Dollars', 'BSD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (9,'Dollars', 'BBD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (10,'Rubles', 'BYR', 'p.');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (11,'Euro', 'EUR', '€');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (12,'Dollars', 'BZD', 'BZ$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (13,'Dollars', 'BMD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (14,'Bolivianos', 'BOB', '$b');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (15,'Convertible Marka', 'BAM', 'KM');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (16,'Pula', 'BWP', 'P');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (17,'Leva', 'BGN', 'лв');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (18,'Reais', 'BRL', 'R$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (19,'Pounds', 'GBP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (20,'Dollars', 'BND', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (21,'Riels', 'KHR', '៛');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (22,'Dollars', 'CAD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (23,'Dollars', 'KYD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (24,'Pesos', 'CLP', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (25,'Yuan Renminbi', 'CNY', '¥');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (26,'Pesos', 'COP', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (27,'Colón', 'CRC', '₡');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (28,'Kuna', 'HRK', 'kn');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (29,'Pesos', 'CUP', '₱');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (30,'Koruny', 'CZK', 'Kč');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (31,'Kroner', 'DKK', 'kr');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (32,'Pesos', 'DOP ', 'RD$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (33,'Dollars', 'XCD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (34,'Pounds', 'EGP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (35,'Colones', 'SVC', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (36,'Pounds', 'FKP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (37,'Dollars', 'FJD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (38,'Cedis', 'GHC', '¢');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (39,'Pounds', 'GIP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (40,'Quetzales', 'GTQ', 'Q');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (41,'Pounds', 'GGP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (42,'Dollars', 'GYD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (43,'Lempiras', 'HNL', 'L');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (44,'Dollars', 'HKD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (45,'Forint', 'HUF', 'Ft');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (46,'Kronur', 'ISK', 'kr');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (47,'Rupees', 'INR', 'Rp');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (48,'Rupiahs', 'IDR', 'Rp');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (49,'Rials', 'IRR', '﷼');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (50,'Pounds', 'IMP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (51,'New Shekels', 'ILS', '₪');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (52,'Dollars', 'JMD', 'J$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (53,'Yen', 'JPY', '¥');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (54,'Pounds', 'JEP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (55,'Tenge', 'KZT', 'лв');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (56,'Won', 'KPW', '₩');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (57,'Won', 'KRW', '₩');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (58,'Soms', 'KGS', 'лв');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (59,'Kips', 'LAK', '₭');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (60,'Lati', 'LVL', 'Ls');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (61,'Pounds', 'LBP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (62,'Dollars', 'LRD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (63,'Switzerland Francs', 'CHF', 'CHF');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (64,'Litai', 'LTL', 'Lt');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (65,'Denars', 'MKD', 'ден');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (66,'Ringgits', 'MYR', 'RM');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (67,'Rupees', 'MUR', '₨');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (68,'Pesos', 'MXN', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (69,'Tugriks', 'MNT', '₮');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (70,'Meticais', 'MZN', 'MT');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (71,'Dollars', 'NAD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (72,'Rupees', 'NPR', '₨');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (73,'Guilders', 'ANG', 'ƒ');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (74,'Dollars', 'NZD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (75,'Cordobas', 'NIO', 'C$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (76,'Nairas', 'NGN', '₦');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (77,'Krone', 'NOK', 'kr');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (78,'Rials', 'OMR', '﷼');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (79,'Rupees', 'PKR', '₨');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (80,'Balboa', 'PAB', 'B/.');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (81,'Guarani', 'PYG', 'Gs');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (82,'Nuevos Soles', 'PEN', 'S/.');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (83,'Pesos', 'PHP', 'Php');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (84,'Zlotych', 'PLN', 'zł');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (85,'Rials', 'QAR', '﷼');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (86,'New Lei', 'RON', 'lei');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (87,'Rubles', 'RUB', 'руб');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (88,'Pounds', 'SHP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (89,'Riyals', 'SAR', '﷼');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (90,'Dinars', 'RSD', 'Дин.');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (91,'Rupees', 'SCR', '₨');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (92,'Dollars', 'SGD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (93,'Dollars', 'SBD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (94,'Shillings', 'SOS', 'S');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (95,'Rand', 'ZAR', 'R');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (96,'Rupees', 'LKR', '₨');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (97,'Kronor', 'SEK', 'kr');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (98,'Dollars', 'SRD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (99,'Pounds', 'SYP', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (100,'New Dollars', 'TWD', 'NT$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (101,'Baht', 'THB', '฿');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (102,'Dollars', 'TTD', 'TT$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (103,'Lira', 'TRY', '₺');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (104,'Liras', 'TRL', '£');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (105,'Dollars', 'TVD', '$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (106,'Hryvnia', 'UAH', '₴');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (107,'Pesos', 'UYU', '$U');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (108,'Sums', 'UZS', 'лв');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (109,'Bolivares Fuertes', 'VEF', 'Bs');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (110,'Dong', 'VND', '₫');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (111,'Rials', 'YER', '﷼');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (112,'Zimbabwe Dollars', 'ZWD', 'Z$');
INSERT [dbo].[Currency] ([Id], [CurrencyName], [Code], [Symbol]) VALUES (113,'Rupees', 'INR', '₹');

SET IDENTITY_INSERT [dbo].[Currency] OFF 
GO