using DocumentFormat.OpenXml.Office2016.Excel;
using GoFoodBeverage.Common.Constants;
using System;

namespace GoFoodBeverage.Payment.VNPay.Model
{
    public class VNPayRefundRequestModel
    {
        /// <summary>
        /// The id is automatically generated by go FnB for each transaction refund request.
        /// This code is unique to distinguish transaction refund requests.
        /// No duplicates within the day.
        /// </summary>
        /// <value>Type: Alphanumeric[1,32]</value>
        public Guid RequestId { get; set; }

        /// <summary>
        /// The payment transaction Id of the merchant system to send VNPAY payment request.
        /// </summary>
        /// <value>Type: Alphanumeric[1,100]</value>
        public Guid TransactionId { get; set; }

        /// <summary>
        /// Type of transaction at VNPAY system:
        /// 02: Full refund transaction(vnp_TransactionType= 02)
        /// 03: Transaction partially refunded(vnp_TransactionType= 03)
        /// </summary>
        public string TransactionType { get; set; }

        /// <summary>
        /// Amount refunded to the customer. 
        /// This amount is less than or equal to the amount of the transaction.
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// Description of request information (Request description).
        /// </summary>
        public string OrderInfo { get; set; }

        /// <summary>
        /// Time to record transactions at Go FnB's website in GMT+7, format: yyyyMMddHHmmss
        /// </summary>
        public string TransDate { get; set; }

        /// <summary>
        /// User info create refund request
        /// </summary>
        public string CreateBy { get; set; }

        /// <summary>
        /// Time to generate request complete(Request Date)
        /// </summary>
        public DateTime CreateDate { get; set; }

        /// <summary>
        /// Time to generate request complete (CreateDate) GMT+7, format: yyyyMMddHHmmss
        /// </summary>
        public string VnPayCreateDate
        {
            get
            {
                TimeZoneInfo tzi = TimeZoneInfo.FindSystemTimeZoneById(TimeZoneConstants.AsiaStandardTimeCode);
                var vnpayDateTime = TimeZoneInfo.ConvertTimeFromUtc(CreateDate, tzi);

                return vnpayDateTime.VnPayFormatDate();
            }
        }

        #region Optional
        /// <summary>
        /// Transaction code recorded at VNPAY system
        /// </summary>
        public string TransactionNo { get; set; }
        #endregion
    }
}
