using GoFoodBeverage.Domain.Enums;
using System;

namespace GoFoodBeverage.Models.Order
{
    /// <summary>
    /// This class is used for Ahamove order history only
    /// </summary>
    public class OrderDeliveryHistoryModel 
    {
        public string UpdateDeliveryStatusRequest { get; set; }

        public Guid? StoreId { get; set; }

        public Guid? BranchId { get; set; }

        public Guid? ShiftId { get; set; }

        public Guid? CustomerId { get; set; }

        public Guid? PromotionId { get; set; }

        public Guid? AreaTableId { get; set; }

        public Guid? OrderDeliveryId { get; set; }

        public Guid? DeliveryMethodId { get; set; }

        public string Note { get; set; }
        /// <summary>
        /// Order status
        /// </summary>
        public EnumOrderStatus StatusId { get; set; }

        /// <summary>
        /// Order payment status
        /// </summary>
        public EnumOrderPaymentStatus? OrderPaymentStatusId { get; set; }

        public EnumOrderType OrderTypeId { get; set; }

        public EnumPaymentMethod PaymentMethodId { get; set; }

        public string Code { get; set; }

        public string StringCode
        {
            get
            {
                return $"{OrderTypeId.GetFirstCharacter()}{Code}";
            }
        }

        /// <summary>
        /// Sum all original price of product items, toppings, fees
        /// </summary>
        public decimal OriginalPrice { get; set; }

        /// <summary>
        /// Sum total discount of all product items in order, promotion
        /// </summary>
        public decimal TotalDiscountAmount { get; set; }

        public decimal PriceAfterDiscount { get; set; }

        public decimal TotalFee { get; set; }

        public bool IsPromotionDiscountPercentage { get; set; }

        /// <summary>
        /// Total discount value of promotion
        /// </summary>
        public decimal PromotionDiscountValue { get; set; }

        /// <summary>
        /// The promotion name apply for this order
        /// </summary>
        public string PromotionName { get; set; }

        /// <summary>
        /// Customer discount value from member shift
        /// </summary>
        public decimal CustomerDiscountAmount { get; set; }

        public string CustomerMemberShipLevel { get; set; }

        /// <summary>
        /// Sum total cost of all product items in an order
        /// </summary>
        public decimal TotalCost { get; set; }

        public string CashierName { get; set; }

        public Guid? PlatformId { get; set; }
        /// <summary>
        /// This field stored all related data to this order
        /// </summary>
        public string RestoreData { get; set; }

        public decimal DeliveryFee { get; set; }

        public decimal TotalTax { get; set; }

        /// <summary>
        /// Money given by customer
        /// </summary>
        public decimal ReceivedAmount { get; set; }

        public decimal Change { get; set; }

        /// <summary>
        /// OrderId generated by Ahamove third party, Example: "1YQJVY"
        /// </summary>
        public string AhamoveOrderId { get; set; }
    }
}
